### ISSUE TITLE
安徽电信与安徽移动均无法正常连接,手机网络也试了打不开

### ISSUE THREAD

**Issue by kaishi961125** [BurningC4/Chinese-IPTV#14]
![image](https://user-images.githubusercontent.com/81787436/186075846-f785d905-06ba-46a2-9d64-b9eb63d431f1.png)
![image](https://user-images.githubusercontent.com/81787436/186075868-5c5bddd8-fe6f-4086-a9d4-5d06db32fdb2.png)

**Comment by BurningC4** [comment]
你现在可以再试试了，如果还不好使说明移动锁区了？
