### ISSUE TITLE
不是提问题，就是告诉你刚刚支持了你一瓶啤酒

### ISSUE THREAD

**Issue by BenBenJian** [BurningC4/Chinese-IPTV#7]
刚好看冬奥会，感谢感谢！期待持续更新呀。

很稳定！！！！

**Comment by BurningC4** [comment]
> 刚好看冬奥会，感谢感谢！期待持续更新呀。
> 
> 很稳定！！！！

谢谢！

**Comment by BenBenJian** [comment]
能提供稍微低一点流量的源吗？4k吃不消啊

**Comment by BurningC4** [comment]
大多数节目源应该不是4K的，而且我尝试打开低分辨率源的时候发现已经都没有了。
我也觉得有点吃不消…
