### ISSUE TITLE
链接在中国大陆以外无法使用

### ISSUE THREAD

**Issue by iMrLopez** [BurningC4/Chinese-IPTV#9]
试图使用这些来自美国的链接，但没有用，有什么帮助吗？ 用谷歌翻译，不好意思中文不好

**Comment by BurningC4** [comment]
基本上没有可能在中国大陆以外的地方使用这些链接，它们都是由中国移动的苏州分公司提供的，目的是为当地用户提供iptv服务，但是在中国大陆其他地方也能使用。
建议你尝试 lylehust/Chinese-IPTV
